default:
  outputs:
    dev:
      dataset: google_drive
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/kato_tsuyoshi/workspace/dbt/psychic-karma-391001-50cc7ae2d836.json
      location: US
      method: service-account
      priority: interactive
      project: psychic-karma-391001
      threads: 1
      type: bigquery
  target: dev
